kind = "app"
categories = ["Graphics", "Photography"]
icon = "assets/app-icon/hicolor/256x256/apps/io.github.teh_natsu.lightkub.png"

[linux.x86_64]
asset = "lightkub-{version}-linux-x86_64.tar.gz"
exec = "lightkub-{version}-linux-x86_64/bin/lightkub"

[linux.aarch64]
asset = "lightkub-{version}-linux-aarch64.tar.gz"
exec = "lightkub-{version}-linux-aarch64/bin/lightkub"
